gitea_urls:
  api: https://git.kernel.fun/api/v1
  download: https://git.kernel.fun
release:
  gitea:
    owner: chapati.systems
    name: covpeek
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  # note that this is an array of nfpm configs
  -
    # Name of the package.
    # Default: ProjectName
    # Templates: allowed (since v1.18)
    package_name: covpeek

    # Your app's vendor.
    vendor: Chapati Systems GmbH

    # Your app's homepage.
    homepage: https://chapati.systems/covpeek

    # Your app's maintainer (probably you).
    maintainer: Christoph Miksche <covpeek25@chapati.systems>

    # Your app's description.
    description: |-
      Automatically updates lots of Software which has no built-in auto update functionality.

    # Your app's license.
    license: AGPL-3.0

    # Formats to be generated.
    formats:
      - deb

    # Packages your package depends on. (overridable)
    dependencies:
      - git

    bindir: /usr/bin

    # Version Release.
    release: 1

    # Section.
    section: default

    # Priority.
    priority: extra
